---
title: "Statistics 1 | R lab"
author: "Alberto Caimo"
output: learnr::tutorial
runtime: shiny_prerendered
---

```{r setup, include=FALSE}
library(learnr)
knitr::opts_chunk$set(echo = FALSE)
```


### Discrete random variables

+ Suppose $X \sim Binomial(n = 10, p = 0.2).$ Find $\Pr(X = 3 \mid X < 6).$
```{r binomial, exercise = TRUE}

```
**Solution: `r dbinom(3, 10, 0.2) / pbinom(5, 10, 0.2)`**

+ Suppose $X \sim Poisson(\lambda = 8).$ Find $\Pr(X < 4 \cup X > 9).$
```{r poisson, exercise = TRUE}

```
**Solution: `r ppois(3, 8) + ppois(9, 8, lower.tail = FALSE)`**

### Continuous random variables

+ Suppose $X$ is a (standard logistic) random variable with PDF: $f(x)=\dfrac{e^{x}}{\left(1+e^{x}\right)^{2}},\ x \in \mathbb{R}.$ Find $\Pr(-2 < X < 2).$
```{r logistic, exercise = TRUE}

```
**Solution: `r f <- function(x) exp(x) / ((1 + exp(x))^2); integrate(f, -2, 2)$value`**

+ Suppose $X \sim \mathcal{N}(\mu = -3, \sigma^2 = 9).$ Find $\Pr(X > 0 \mid X < 2).$
```{r normal, exercise = TRUE}

```
**Solution: `r (pnorm(2, -3, 3) - pnorm(0, -3, 3)) / pnorm(2, -3, 3)`**

+ Suppose $X \sim \mathcal{N}(\mu = 1.3, \sigma^2 = 36).$ Find $x$ such that $\Pr(X > x) = 0.36.$
```{r quantile, exercise = TRUE}

```
**Solution: `r qnorm(1 - 0.36, 1.3, 6)`**
